import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'de' | 'en' | 'tr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  de: {
    'nav.home': 'Startseite',
    'nav.product': 'Produkt',
    'nav.howItWorks': 'So funktioniert es',
    'nav.safety': 'Sicherheit & Datenschutz',
    'nav.faq': 'FAQ',
    'nav.contact': 'Kontakt',
    'nav.childApp': 'Kinder-App',
    'nav.parentApp': 'Eltern-App',
    'nav.schoolApp': 'Schul-App',
    'nav.demo': 'Demo',
    'hero.title': 'Schnelle Hilfe für Kinder in Not',
    'hero.subtitle': 'SafeKid ermöglicht Kindern, in Momenten der Angst, bei Mobbing oder Gefahr diskret und schnell um Hilfe zu bitten. Eltern und Schulen werden automatisch benachrichtigt.',
    'hero.cta.parent': 'Für Eltern',
    'hero.cta.child': 'Für Kinder',
    'hero.cta.school': 'Für Schulen',
    'features.title': 'Funktionen',
    'features.sos.title': 'SOS-Knopf',
    'features.sos.desc': 'Ein großer, einfacher Knopf für schnelle Hilfe',
    'features.location.title': 'Standortübermittlung',
    'features.location.desc': 'Automatische GPS-Ortung im Notfall',
    'features.instant.title': 'Sofortige Benachrichtigung',
    'features.instant.desc': 'Eltern werden umgehend informiert',
    'product.title': 'Das SafeKid System',
    'product.subtitle': 'Drei Benutzergruppen arbeiten zusammen für maximale Sicherheit',
    'product.child.title': 'Kinder-App',
    'product.child.desc': 'Einfache, kindgerechte Oberfläche mit großem SOS-Knopf für schnelle Hilfe in Notfällen.',
    'product.parent.title': 'Eltern-Dashboard',
    'product.parent.desc': 'Eltern erhalten alle Notrufe ihrer Kinder sofort mit Live-Standort und können direkt reagieren.',
    'product.school.title': 'Schul-Dashboard',
    'product.school.desc': 'Schulen werden benachrichtigt, wenn Kinder in einem 1 km Radius um die Schule einen Notruf absetzen.',
    'product.howItWorks.title': 'So funktioniert die Benachrichtigungslogik',
    'product.howItWorks.step1.title': 'Kind löst SOS aus',
    'product.howItWorks.step1.desc': 'Das Kind drückt den SOS-Knopf in der App. Der aktuelle GPS-Standort wird sofort erfasst und verschlüsselt übertragen.',
    'product.howItWorks.step2.title': 'Eltern werden immer benachrichtigt',
    'product.howItWorks.step2.desc': 'Alle verknüpften Eltern erhalten sofort eine Benachrichtigung mit dem Live-Standort des Kindes, unabhängig davon wo sich das Kind befindet.',
    'product.howItWorks.step3.title': 'Schulen werden bei Nähe benachrichtigt',
    'product.howItWorks.step3.desc': 'Wenn sich das Kind im Umkreis von 1 km um eine registrierte Schule befindet, wird auch die Schule benachrichtigt. Befindet sich das Kind außerhalb dieses Radius, erhält die Schule keine Benachrichtigung.',
    'product.privacy.title': 'Datenschutz durch intelligente Benachrichtigungslogik',
    'product.privacy.desc': 'Schulen erhalten nur Benachrichtigungen, wenn Kinder sich in Schulnähe befinden. Dies schützt die Privatsphäre der Familien und stellt sicher, dass Schulen nur relevante Notfälle in ihrem Zuständigkeitsbereich sehen.',
    'howItWorks.title': 'So funktioniert SafeKid',
    'howItWorks.subtitle': 'Vier einfache Schritte zu mehr Sicherheit',
    'howItWorks.step1': 'Kind drückt SOS-Knopf',
    'howItWorks.step1.desc': 'Das Kind drückt den großen roten SOS-Knopf in der App, wenn es Hilfe benötigt.',
    'howItWorks.step2': 'GPS-Standort wird erfasst',
    'howItWorks.step2.desc': 'Die App erfasst automatisch den GPS-Standort des Kindes und berechnet die Entfernung zu registrierten Schulen.',
    'howItWorks.step3': 'Eltern und Schulen erhalten Benachrichtigung',
    'howItWorks.step3.desc': 'Eltern erhalten immer eine Benachrichtigung. Schulen erhalten nur eine Benachrichtigung, wenn das Kind sich im 1 km Radius um die Schule befindet.',
    'howItWorks.step4': 'Sofortige Reaktion möglich',
    'howItWorks.step4.desc': 'Eltern und Schulen sehen den Live-Standort auf einer Karte und können sofort reagieren oder das Kind anrufen.',
    'howItWorks.geofencing.title': 'Geofencing für Schulen',
    'howItWorks.geofencing.desc': 'Schulen werden nur benachrichtigt, wenn sich das Kind innerhalb eines 1 km Radius um die Schule befindet. Dies stellt sicher, dass Schulen nur für Notfälle in ihrer unmittelbaren Nähe zuständig sind.',
    'howItWorks.geofencing.privacy': 'Außerhalb dieses Bereichs bleiben Notfälle privat zwischen Kind und Eltern. Dies schützt die Privatsphäre und reduziert unnötige Benachrichtigungen.',
    'howItWorks.disclaimer.title': 'Wichtiger Hinweis',
    'safety.title': 'Sicherheit & Datenschutz',
    'safety.subtitle': 'Ihre Daten sind bei uns sicher',
    'safety.gdpr.title': 'DSGVO-konform',
    'safety.gdpr.desc': 'Alle Daten werden gemäß der europäischen Datenschutz-Grundverordnung verarbeitet',
    'safety.encryption.title': 'Ende-zu-Ende-Verschlüsselung',
    'safety.encryption.desc': 'Alle Kommunikation ist verschlüsselt',
    'safety.minimal.title': 'Minimale Datenerfassung',
    'safety.minimal.desc': 'Wir erfassen nur die notwendigsten Daten',
    'safety.disclaimer': 'SafeKid ist KEIN Ersatz für Notdienste. Bei akuten Gefahrensituationen bitte 110 oder 112 anrufen.',
    'safety.supportTool': 'SafeKid ist ein unterstützendes Sicherheitstool, kein Ersatz für professionelle Notdienste.',
    'faq.title': 'Häufig gestellte Fragen',
    'faq.q1': 'Ist SafeKid kostenlos?',
    'faq.a1': 'Ja, SafeKid ist ein Schulprojekt und kostenlos verfügbar.',
    'faq.q2': 'Ab welchem Alter ist SafeKid geeignet?',
    'faq.a2': 'SafeKid ist für Kinder und Jugendliche ab 6 Jahren konzipiert.',
    'faq.q3': 'Ersetzt SafeKid den Notruf 110/112?',
    'faq.a3': 'Nein! Bei akuten Gefahrensituationen bitte immer die Polizei (110) oder Feuerwehr/Rettung (112) anrufen.',
    'faq.q4': 'Wie genau ist die Standortbestimmung?',
    'faq.a4': 'Die Genauigkeit hängt vom GPS-Empfang ab, liegt aber meist bei 5-10 Metern.',
    'contact.title': 'Kontakt & Projekt-Info',
    'contact.subtitle': 'Dies ist ein Fachabitur-Projekt',
    'contact.school': 'Schule',
    'contact.project': 'Projekttyp',
    'contact.year': 'Schuljahr',
    'contact.disclaimer': 'SafeKid ist ein Schulprojekt und dient zu Demonstrationszwecken. Es handelt sich um einen Prototyp.',
    'childApp.title': 'SOS',
    'childApp.button': 'Hilfe rufen',
    'childApp.sending': 'Sende Notruf...',
    'childApp.sent': 'Notruf gesendet!',
    'childApp.location': 'Standort wird ermittelt...',
    'parentApp.title': 'Notfall-Übersicht',
    'parentApp.noEvents': 'Keine aktiven Notfälle',
    'parentApp.activeEvent': 'Aktiver Notfall!',
    'parentApp.child': 'Kind',
    'parentApp.time': 'Zeit',
    'parentApp.location': 'Standort',
    'parentApp.actions': 'Aktionen',
    'parentApp.call': 'Kind anrufen',
    'parentApp.acknowledge': 'Bestätigen',
    'parentApp.resolve': 'Abschließen',
    'parentApp.emergency': 'Notruf 110/112',
    'footer.tagline': 'Sicherheit für Kinder, Beruhigung für Eltern',
    'footer.project': 'Ein Fachabitur-Projekt',
    'footer.links': 'Links',
    'footer.legal': 'Rechtliches',
  },
  en: {
    'nav.home': 'Home',
    'nav.product': 'Product',
    'nav.howItWorks': 'How It Works',
    'nav.safety': 'Safety & Privacy',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.childApp': 'Child App',
    'nav.parentApp': 'Parent App',
    'nav.schoolApp': 'School App',
    'nav.demo': 'Demo',
    'hero.title': 'Quick Help for Children in Need',
    'hero.subtitle': 'SafeKid enables children to ask for help quickly and discreetly in moments of fear, bullying, or danger. Parents and schools are automatically notified.',
    'hero.cta.parent': 'For Parents',
    'hero.cta.child': 'For Children',
    'hero.cta.school': 'For Schools',
    'features.title': 'Features',
    'features.sos.title': 'SOS Button',
    'features.sos.desc': 'One large, simple button for quick help',
    'features.location.title': 'Location Sharing',
    'features.location.desc': 'Automatic GPS tracking in emergencies',
    'features.instant.title': 'Instant Notification',
    'features.instant.desc': 'Parents are notified immediately',
    'product.title': 'The SafeKid System',
    'product.subtitle': 'Three user groups working together for maximum safety',
    'product.child.title': 'Child App',
    'product.child.desc': 'Simple, child-friendly interface with large SOS button for quick help in emergencies.',
    'product.parent.title': 'Parent Dashboard',
    'product.parent.desc': 'Parents receive all emergency calls from their children immediately with live location and can respond directly.',
    'product.school.title': 'School Dashboard',
    'product.school.desc': 'Schools are notified when children within a 1 km radius of the school send an emergency call.',
    'product.howItWorks.title': 'How the notification logic works',
    'product.howItWorks.step1.title': 'Child triggers SOS',
    'product.howItWorks.step1.desc': 'The child presses the SOS button in the app. The current GPS location is immediately captured and transmitted encrypted.',
    'product.howItWorks.step2.title': 'Parents are always notified',
    'product.howItWorks.step2.desc': 'All linked parents immediately receive a notification with the child\'s live location, regardless of where the child is located.',
    'product.howItWorks.step3.title': 'Schools are notified when nearby',
    'product.howItWorks.step3.desc': 'If the child is within a 1 km radius of a registered school, the school is also notified. If the child is outside this radius, the school receives no notification.',
    'product.privacy.title': 'Privacy through intelligent notification logic',
    'product.privacy.desc': 'Schools only receive notifications when children are near the school. This protects family privacy and ensures schools only see relevant emergencies in their area of responsibility.',
    'howItWorks.title': 'How SafeKid Works',
    'howItWorks.subtitle': 'Four simple steps to greater safety',
    'howItWorks.step1': 'Child presses SOS button',
    'howItWorks.step1.desc': 'The child presses the large red SOS button in the app when they need help.',
    'howItWorks.step2': 'GPS location is captured',
    'howItWorks.step2.desc': 'The app automatically captures the child\'s GPS location and calculates the distance to registered schools.',
    'howItWorks.step3': 'Parents and schools receive notification',
    'howItWorks.step3.desc': 'Parents always receive a notification. Schools only receive a notification if the child is within a 1 km radius of the school.',
    'howItWorks.step4': 'Immediate response possible',
    'howItWorks.step4.desc': 'Parents and schools see the live location on a map and can immediately respond or call the child.',
    'howItWorks.geofencing.title': 'Geofencing for schools',
    'howItWorks.geofencing.desc': 'Schools are only notified when the child is within a 1 km radius of the school. This ensures schools are only responsible for emergencies in their immediate vicinity.',
    'howItWorks.geofencing.privacy': 'Outside this area, emergencies remain private between child and parents. This protects privacy and reduces unnecessary notifications.',
    'howItWorks.disclaimer.title': 'Important notice',
    'safety.title': 'Safety & Privacy',
    'safety.subtitle': 'Your data is safe with us',
    'safety.gdpr.title': 'GDPR Compliant',
    'safety.gdpr.desc': 'All data is processed in accordance with European data protection regulations',
    'safety.encryption.title': 'End-to-End Encryption',
    'safety.encryption.desc': 'All communication is encrypted',
    'safety.minimal.title': 'Minimal Data Collection',
    'safety.minimal.desc': 'We only collect the most necessary data',
    'safety.disclaimer': 'SafeKid is NOT a replacement for emergency services. In acute danger situations, please call 110 or 112.',
    'safety.supportTool': 'SafeKid is a supportive safety tool, not a replacement for professional emergency services.',
    'faq.title': 'Frequently Asked Questions',
    'faq.q1': 'Is SafeKid free?',
    'faq.a1': 'Yes, SafeKid is a school project and available for free.',
    'faq.q2': 'What age is SafeKid suitable for?',
    'faq.a2': 'SafeKid is designed for children and teenagers aged 6 and above.',
    'faq.q3': 'Does SafeKid replace emergency calls 110/112?',
    'faq.a3': 'No! In acute danger situations, always call police (110) or fire/ambulance (112).',
    'faq.q4': 'How accurate is the location tracking?',
    'faq.a4': 'Accuracy depends on GPS reception, but is usually within 5-10 meters.',
    'contact.title': 'Contact & Project Info',
    'contact.subtitle': 'This is a Fachabitur project',
    'contact.school': 'School',
    'contact.project': 'Project Type',
    'contact.year': 'School Year',
    'contact.disclaimer': 'SafeKid is a school project for demonstration purposes. This is a prototype.',
    'childApp.title': 'SOS',
    'childApp.button': 'Call for Help',
    'childApp.sending': 'Sending emergency...',
    'childApp.sent': 'Emergency sent!',
    'childApp.location': 'Getting location...',
    'parentApp.title': 'Emergency Overview',
    'parentApp.noEvents': 'No active emergencies',
    'parentApp.activeEvent': 'Active Emergency!',
    'parentApp.child': 'Child',
    'parentApp.time': 'Time',
    'parentApp.location': 'Location',
    'parentApp.actions': 'Actions',
    'parentApp.call': 'Call Child',
    'parentApp.acknowledge': 'Acknowledge',
    'parentApp.resolve': 'Resolve',
    'parentApp.emergency': 'Emergency 110/112',
    'footer.tagline': 'Safety for children, peace of mind for parents',
    'footer.project': 'A Fachabitur Project',
    'footer.links': 'Links',
    'footer.legal': 'Legal',
  },
  tr: {
    'nav.home': 'Ana Sayfa',
    'nav.product': 'Ürün',
    'nav.howItWorks': 'Nasıl Çalışır',
    'nav.safety': 'Güvenlik & Gizlilik',
    'nav.faq': 'SSS',
    'nav.contact': 'İletişim',
    'nav.childApp': 'Çocuk Uygulaması',
    'nav.parentApp': 'Ebeveyn Uygulaması',
    'nav.schoolApp': 'Okul Uygulaması',
    'nav.demo': 'Demo',
    'hero.title': 'İhtiyacı Olan Çocuklar İçin Hızlı Yardım',
    'hero.subtitle': 'SafeKid, çocukların korku, zorbalık veya tehlike anlarında gizlice ve hızlıca yardım istemelerini sağlar. Ebeveynler ve okullar otomatik olarak bilgilendirilir.',
    'hero.cta.parent': 'Ebeveynler İçin',
    'hero.cta.child': 'Çocuklar İçin',
    'hero.cta.school': 'Okullar İçin',
    'features.title': 'Özellikler',
    'features.sos.title': 'SOS Butonu',
    'features.sos.desc': 'Hızlı yardım için büyük, basit bir buton',
    'features.location.title': 'Konum Paylaşımı',
    'features.location.desc': 'Acil durumlarda otomatik GPS takibi',
    'features.instant.title': 'Anında Bildirim',
    'features.instant.desc': 'Ebeveynler hemen bilgilendirilir',
    'product.title': 'SafeKid Sistemi',
    'product.subtitle': 'Maksimum güvenlik için birlikte çalışan üç kullanıcı grubu',
    'product.child.title': 'Çocuk Uygulaması',
    'product.child.desc': 'Acil durumlarda hızlı yardım için büyük SOS butonu ile basit, çocuk dostu arayüz.',
    'product.parent.title': 'Ebeveyn Kontrol Paneli',
    'product.parent.desc': 'Ebeveynler çocuklarından gelen tüm acil çağrıları canlı konum ile anında alır ve doğrudan yanıt verebilir.',
    'product.school.title': 'Okul Kontrol Paneli',
    'product.school.desc': 'Okullar, okulun 1 km yarıçapı içindeki çocuklar acil çağrı gönderdiğinde bilgilendirilir.',
    'product.howItWorks.title': 'Bildirim mantığı nasıl çalışır',
    'product.howItWorks.step1.title': 'Çocuk SOS tetikler',
    'product.howItWorks.step1.desc': 'Çocuk uygulamada SOS butonuna basar. Mevcut GPS konumu hemen yakalanır ve şifreli olarak iletilir.',
    'product.howItWorks.step2.title': 'Ebeveynler her zaman bilgilendirilir',
    'product.howItWorks.step2.desc': 'Bağlı tüm ebeveynler, çocuğun nerede olduğuna bakılmaksızın, çocuğun canlı konumuyla birlikte hemen bir bildirim alır.',
    'product.howItWorks.step3.title': 'Okullar yakındayken bilgilendirilir',
    'product.howItWorks.step3.desc': 'Çocuk kayıtlı bir okulun 1 km yarıçapı içindeyse, okul da bilgilendirilir. Çocuk bu yarıçapın dışındaysa, okul bildirim almaz.',
    'product.privacy.title': 'Akıllı bildirim mantığıyla gizlilik',
    'product.privacy.desc': 'Okullar yalnızca çocuklar okula yakınken bildirim alır. Bu aile gizliliğini korur ve okulların yalnızca sorumluluk alanlarındaki ilgili acil durumları görmelerini sağlar.',
    'howItWorks.title': 'SafeKid Nasıl Çalışır',
    'howItWorks.subtitle': 'Daha fazla güvenlik için dört basit adım',
    'howItWorks.step1': 'Çocuk SOS butonuna basar',
    'howItWorks.step1.desc': 'Çocuk yardıma ihtiyaç duyduğunda uygulamadaki büyük kırmızı SOS butonuna basar.',
    'howItWorks.step2': 'GPS konumu alınır',
    'howItWorks.step2.desc': 'Uygulama otomatik olarak çocuğun GPS konumunu yakalar ve kayıtlı okullara olan mesafeyi hesaplar.',
    'howItWorks.step3': 'Ebeveynler ve okullar bildirim alır',
    'howItWorks.step3.desc': 'Ebeveynler her zaman bildirim alır. Okullar yalnızca çocuk okulun 1 km yarıçapı içindeyse bildirim alır.',
    'howItWorks.step4': 'Hemen yanıt mümkün',
    'howItWorks.step4.desc': 'Ebeveynler ve okullar harita üzerinde canlı konumu görür ve hemen yanıt verebilir veya çocuğu arayabilir.',
    'howItWorks.geofencing.title': 'Okullar için coğrafi çit',
    'howItWorks.geofencing.desc': 'Okullar yalnızca çocuk okulun 1 km yarıçapı içinde olduğunda bilgilendirilir. Bu, okulların yalnızca yakın çevrelerindeki acil durumlardan sorumlu olmalarını sağlar.',
    'howItWorks.geofencing.privacy': 'Bu alanın dışında, acil durumlar çocuk ve ebeveynler arasında özel kalır. Bu gizliliği korur ve gereksiz bildirimleri azaltır.',
    'howItWorks.disclaimer.title': 'Önemli not',
    'safety.title': 'Güvenlik & Gizlilik',
    'safety.subtitle': 'Verileriniz bizimle güvende',
    'safety.gdpr.title': 'GDPR Uyumlu',
    'safety.gdpr.desc': 'Tüm veriler Avrupa veri koruma düzenlemelerine uygun olarak işlenir',
    'safety.encryption.title': 'Uçtan Uca Şifreleme',
    'safety.encryption.desc': 'Tüm iletişim şifrelenir',
    'safety.minimal.title': 'Minimum Veri Toplama',
    'safety.minimal.desc': 'Sadece en gerekli verileri topluyoruz',
    'safety.disclaimer': 'SafeKid acil servisler için bir yerine GEÇMEZ. Akut tehlike durumlarında lütfen 110 veya 112yi arayın.',
    'safety.supportTool': 'SafeKid destekleyici bir güvenlik aracıdır, profesyonel acil servislerin yerine geçmez.',
    'faq.title': 'Sıkça Sorulan Sorular',
    'faq.q1': 'SafeKid ücretsiz mi?',
    'faq.a1': 'Evet, SafeKid bir okul projesidir ve ücretsiz olarak sunulmaktadır.',
    'faq.q2': 'SafeKid kaç yaş için uygundur?',
    'faq.a2': 'SafeKid, 6 yaş ve üzeri çocuklar ve gençler için tasarlanmıştır.',
    'faq.q3': 'SafeKid, 110/112 acil çağrılarının yerini alır mı?',
    'faq.a3': 'Hayır! Akut tehlike durumlarında her zaman polisi (110) veya itfaiye/ambulansı (112) arayın.',
    'faq.q4': 'Konum takibi ne kadar doğru?',
    'faq.a4': 'Doğruluk GPS alımına bağlıdır, ancak genellikle 5-10 metre içindedir.',
    'contact.title': 'İletişim & Proje Bilgisi',
    'contact.subtitle': 'Bu bir Fachabitur projesidir',
    'contact.school': 'Okul',
    'contact.project': 'Proje Türü',
    'contact.year': 'Okul Yılı',
    'contact.disclaimer': 'SafeKid gösteri amaçlı bir okul projesidir. Bu bir prototiptir.',
    'childApp.title': 'SOS',
    'childApp.button': 'Yardım Çağır',
    'childApp.sending': 'Acil durum gönderiliyor...',
    'childApp.sent': 'Acil durum gönderildi!',
    'childApp.location': 'Konum alınıyor...',
    'parentApp.title': 'Acil Durum Özeti',
    'parentApp.noEvents': 'Aktif acil durum yok',
    'parentApp.activeEvent': 'Aktif Acil Durum!',
    'parentApp.child': 'Çocuk',
    'parentApp.time': 'Zaman',
    'parentApp.location': 'Konum',
    'parentApp.actions': 'Eylemler',
    'parentApp.call': 'Çocuğu Ara',
    'parentApp.acknowledge': 'Onayla',
    'parentApp.resolve': 'Çöz',
    'parentApp.emergency': 'Acil 110/112',
    'footer.tagline': 'Çocuklar için güvenlik, ebeveynler için huzur',
    'footer.project': 'Bir Fachabitur Projesi',
    'footer.links': 'Bağlantılar',
    'footer.legal': 'Yasal',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('de');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
